-- MySQL Script generated by MySQL Workbench
-- Sun May 16 18:18:53 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema carcenter
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema carcenter
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `heroku_107cceeb022a6e3` DEFAULT CHARACTER SET utf8mb4 ;
USE `heroku_107cceeb022a6e3` ;

-- -----------------------------------------------------
-- Table `heroku_107cceeb022a6e3`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroku_107cceeb022a6e3`.`clientes` (
  `tipo_documento` VARCHAR(2) NOT NULL,
  `documento` INT(11) NOT NULL,
  `primer_nombre` VARCHAR(30) NOT NULL,
  `segundo_nombre` VARCHAR(30) NOT NULL,
  `primer_apellido` VARCHAR(30) NOT NULL,
  `segundo_apellido` VARCHAR(30) NOT NULL,
  `celular` VARCHAR(10) NOT NULL,
  `direccion` VARCHAR(200) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `estado` CHAR(1) NULL DEFAULT NULL,
  PRIMARY KEY (`tipo_documento`, `documento`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `heroku_107cceeb022a6e3`.`facturas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroku_107cceeb022a6e3`.`facturas` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT,
  `precio_total` DECIMAL(10,2) NOT NULL,
  `precio_impuesto` DECIMAL(10,2) NOT NULL,
  `precio_descuento` DECIMAL(10,2) NOT NULL,
  `fecha` DATE NOT NULL,
  `estado` CHAR(1) NOT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `heroku_107cceeb022a6e3`.`marcas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroku_107cceeb022a6e3`.`marcas` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre_marca` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `heroku_107cceeb022a6e3`.`vehiculos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroku_107cceeb022a6e3`.`vehiculos` (
  `placa` VARCHAR(6) NOT NULL,
  `color` VARCHAR(30) NOT NULL,
  `cod_marca` INT(11) NOT NULL,
  `cli_documento` INT(11) NOT NULL,
  `cli_tipo_documento` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`placa`),
  INDEX `cod_marca` (`cod_marca` ASC) VISIBLE,
  INDEX `cli_tipo_documento` (`cli_tipo_documento` ASC, `cli_documento` ASC) VISIBLE,
  CONSTRAINT `vehiculos_ibfk_1`
    FOREIGN KEY (`cod_marca`)
    REFERENCES `heroku_107cceeb022a6e3`.`marcas` (`codigo`),
  CONSTRAINT `vehiculos_ibfk_2`
    FOREIGN KEY (`cli_tipo_documento` , `cli_documento`)
    REFERENCES `heroku_107cceeb022a6e3`.`clientes` (`tipo_documento` , `documento`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `heroku_107cceeb022a6e3`.`mecanicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroku_107cceeb022a6e3`.`mecanicos` (
  `tipo_documento` VARCHAR(2) NOT NULL,
  `documento` INT(20) NOT NULL,
  `primer_nombre` VARCHAR(30) NOT NULL,
  `segundo_nombre` VARCHAR(30) NOT NULL,
  `primer_apellido` VARCHAR(30) NOT NULL,
  `segundo_apellido` VARCHAR(30) NOT NULL,
  `celular` VARCHAR(10) NOT NULL,
  `direccion` VARCHAR(200) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `estado` CHAR(1) NOT NULL,
  PRIMARY KEY (`tipo_documento`, `documento`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `heroku_107cceeb022a6e3`.`mantenimientos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroku_107cceeb022a6e3`.`mantenimientos` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT,
  `estado` CHAR(1) NOT NULL,
  `cod_placa` VARCHAR(6) NOT NULL,
  `fecha` DATE NOT NULL,
  `mec_documento` INT(20) NULL DEFAULT NULL,
  `mec_tipo_documento` VARCHAR(2) NULL DEFAULT NULL,
  `precio_total` DECIMAL(10,2) NOT NULL,
  `precio_tope` DECIMAL(10,2) NOT NULL,
  `cod_factura` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `cod_placa` (`cod_placa` ASC) VISIBLE,
  INDEX `mec_tipo_documento` (`mec_tipo_documento` ASC, `mec_documento` ASC) VISIBLE,
  INDEX `cod_factura` (`cod_factura` ASC) VISIBLE,
  CONSTRAINT `mantenimientos_ibfk_2`
    FOREIGN KEY (`cod_placa`)
    REFERENCES `heroku_107cceeb022a6e3`.`vehiculos` (`placa`),
  CONSTRAINT `mantenimientos_ibfk_3`
    FOREIGN KEY (`mec_tipo_documento` , `mec_documento`)
    REFERENCES `heroku_107cceeb022a6e3`.`mecanicos` (`tipo_documento` , `documento`),
  CONSTRAINT `mantenimientos_ibfk_4`
    FOREIGN KEY (`cod_factura`)
    REFERENCES `heroku_107cceeb022a6e3`.`facturas` (`codigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `heroku_107cceeb022a6e3`.`fotos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroku_107cceeb022a6e3`.`fotos` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT,
  `ruta` VARCHAR(200) NOT NULL,
  `cod_mantenimiento` INT(11) NOT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `cod_mantenimiento` (`cod_mantenimiento` ASC) VISIBLE,
  CONSTRAINT `fotos_ibfk_1`
    FOREIGN KEY (`cod_mantenimiento`)
    REFERENCES `heroku_107cceeb022a6e3`.`mantenimientos` (`codigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `heroku_107cceeb022a6e3`.`referencias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroku_107cceeb022a6e3`.`referencias` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT,
  `identificador` VARCHAR(6) NOT NULL,
  `valor` VARCHAR(200) NOT NULL,
  `descripcion` VARCHAR(300) NOT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `heroku_107cceeb022a6e3`.`repuestos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroku_107cceeb022a6e3`.`repuestos` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre_repuesto` VARCHAR(200) NOT NULL,
  `precio_unitario` DECIMAL(10,2) NOT NULL,
  `unidades_inventario` INT(11) NOT NULL,
  `proveedor` VARCHAR(300) NOT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `heroku_107cceeb022a6e3`.`repuestos_x_mantenimiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroku_107cceeb022a6e3`.`repuestos_x_mantenimiento` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT,
  `unidades` INT(11) NOT NULL,
  `tiempo_estimado` INT(11) NOT NULL,
  `cod_mantenimiento` INT(11) NOT NULL,
  `cod_repuesto` INT(11) NOT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `cod_mantenimiento` (`cod_mantenimiento` ASC) VISIBLE,
  INDEX `cod_repuesto` (`cod_repuesto` ASC) VISIBLE,
  CONSTRAINT `repuestos_x_mantenimiento_ibfk_2`
    FOREIGN KEY (`cod_repuesto`)
    REFERENCES `heroku_107cceeb022a6e3`.`repuestos` (`codigo`),
  CONSTRAINT `repuestos_x_mantenimiento_ibfk_3`
    FOREIGN KEY (`cod_mantenimiento`)
    REFERENCES `heroku_107cceeb022a6e3`.`mantenimientos` (`codigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `heroku_107cceeb022a6e3`.`servicios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroku_107cceeb022a6e3`.`servicios` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre_servicio` VARCHAR(100) NOT NULL,
  `precio_minimo` DECIMAL(10,2) NOT NULL,
  `precio_maximo` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `heroku_107cceeb022a6e3`.`servicios_x_mantenimiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroku_107cceeb022a6e3`.`servicios_x_mantenimiento` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT,
  `tiempo_estimado` INT(11) NOT NULL,
  `precio` DECIMAL(10,2) NOT NULL,
  `cod_servicio` INT(11) NOT NULL,
  `cod_mantenimiento` INT(11) NOT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `cod_servicio` (`cod_servicio` ASC) VISIBLE,
  INDEX `cod_mantenimiento` (`cod_mantenimiento` ASC) VISIBLE,
  CONSTRAINT `servicios_x_mantenimiento_ibfk_1`
    FOREIGN KEY (`cod_servicio`)
    REFERENCES `heroku_107cceeb022a6e3`.`servicios` (`codigo`),
  CONSTRAINT `servicios_x_mantenimiento_ibfk_2`
    FOREIGN KEY (`cod_mantenimiento`)
    REFERENCES `heroku_107cceeb022a6e3`.`mantenimientos` (`codigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


INSERT INTO `heroku_107cceeb022a6e3`.`referencias` (`identificador`, `valor`, `descripcion`) VALUES
('VIVA', '19', 'Representa el valor del IVA'),
('DCTM', '50', 'Representa el porcentaje de descuento aplicable sobre los servicios de mano de obra'),
('TDCT', '3000000', 'Representa el valor acumulado de servicios por mano de obra para aplicar descuento'),
('TIDE', 'CC', 'Tipo identificador Cedula Ciudadania'),
('TIDE', 'CE', 'Tipo identificador Cedula Extranjeria'),
('LMDI', '10', 'Limite de registros retornados en la consulta de mecanicos disponibles');


INSERT INTO `heroku_107cceeb022a6e3`.`clientes` (`tipo_documento`, `documento`, `primer_nombre`, `segundo_nombre`, `primer_apellido`, `segundo_apellido`, `celular`, `direccion`, `email`, `estado`) VALUES
('CC', 9545632, 'Jose', 'William', 'Torrez', 'Zapata', '4335487', 'Valle', 'jose@hotmail.com', 'A'),
('CC', 114454546, 'Vanessa', '', 'Arevalo', 'Bohada', '3215654565', 'Bogota', 'vane@gmail.com', 'A'),
('CC', 1147773665, 'Jorge', 'William', 'Ramirez', 'Largo', '3194834044', 'Cll 71 D # 3EN - 53', 'j_wjo@hotmail.com', 'A');


INSERT INTO `heroku_107cceeb022a6e3`.`marcas` (`nombre_marca`) VALUES
('Chevrolet'),
('Mazda'),
('Hyundai');


INSERT INTO `heroku_107cceeb022a6e3`.`vehiculos` (`placa`, `color`, `cod_marca`, `cli_documento`, `cli_tipo_documento`) VALUES
('BVS675', 'rojo', (SELECT `codigo` FROM `heroku_107cceeb022a6e3`.`marcas` WHERE `nombre_marca` = 'Chevrolet'), 114454546, 'CC'),
('CMA564', 'blanco', (SELECT `codigo` FROM `heroku_107cceeb022a6e3`.`marcas` WHERE `nombre_marca` = 'Mazda'), 1147773665, 'CC'),
('IGU444', 'verde', (SELECT `codigo` FROM `heroku_107cceeb022a6e3`.`marcas` WHERE `nombre_marca` = 'Hyundai'), 9545632, 'CC');


INSERT INTO `heroku_107cceeb022a6e3`.`mecanicos` (`tipo_documento`, `documento`, `primer_nombre`, `segundo_nombre`, `primer_apellido`, `segundo_apellido`, `celular`, `direccion`, `email`, `estado`) VALUES
('CC', 44173665, 'Alexander', '', 'Echeverry', '', '3214834044', 'Cll 70F # 3EN - 6', 'echeverry@gmail.com', 'A'),
('CC', 112036545, 'Jairo', '', 'Chavez', '', '4331287', 'Clla 65 F', 'chavez@gmail.com', 'A'),
('CC', 1144758465, 'Vanessa', '', 'Arevalo', '', '3214567895', 'Cota', 'vane@outlook.com', 'A'),
('CE', 54173665, 'Amparo', '', 'Largo', '', '3194856255', 'Cll', 'flor2@gmail.com', 'A'),
('CE', 1144859999, 'Carlos', '', 'Chavez', '', '3214876255', 'Cll', 'carlos@gmail.com', 'A');


INSERT INTO `heroku_107cceeb022a6e3`.`servicios` (`nombre_servicio`, `precio_minimo`, `precio_maximo`) VALUES
('MANO OBRA', '15000.00', '80000.00'),
('LIMPIEZA', '15000.00', '45000.00'),
('REVISION', '15000.00', '30000.00');


INSERT INTO `heroku_107cceeb022a6e3`.`repuestos` (`nombre_repuesto`, `precio_unitario`, `unidades_inventario`, `proveedor`) VALUES
('Bujia', '500.00', 45, 'Bujias SAS'),
('llantas', '87000.00', 15, 'Llantas pro'),
('Pito', '150000.00', 12, 'Pitos Mac');


INSERT INTO `heroku_107cceeb022a6e3`.`mantenimientos` (`estado`, `cod_placa`, `fecha`, `mec_documento`, `mec_tipo_documento`, `precio_total`, `precio_tope`, `cod_factura`) VALUES
('S', 'IGU444', '2021-05-19', NULL, NULL, '0.00', '0.00', NULL),
('T', 'BVS675', '2021-04-05', 44173665, 'CC', '0.00', '0.00', NULL),
('T', 'CMA564', '2021-04-20', 54173665, 'CE', '0.00', '0.00', NULL),
('T', 'IGU444', '2021-04-22', 54173665, 'CE', '0.00', '0.00', NULL),
('T', 'CMA564', '2021-04-23', 1144758465, 'CC', '0.00', '0.00', NULL),
('T', 'CMA564', '2021-04-04', 112036545, 'CC', '0.00', '0.00', NULL),
('S', 'CMA564', '2021-05-16', NULL, NULL, '0.00', '0.00', NULL),
('S', 'CMA564', '2021-05-16', NULL, NULL, '0.00', '700000.00', NULL);


INSERT INTO `heroku_107cceeb022a6e3`.`servicios_x_mantenimiento` (`tiempo_estimado`, `precio`, `cod_servicio`, `cod_mantenimiento`) VALUES
(15, '5000.00', 14, 84),
(45, '1500.00', 14, 94),
(15, '4500.00', 4, 104),
(65, '5500.00', 14, 114),
(23, '7800.00', 24, 124);


INSERT INTO `heroku_107cceeb022a6e3`.`repuestos_x_mantenimiento` (`unidades`, `tiempo_estimado`, `cod_mantenimiento`, `cod_repuesto`) VALUES
(2, 10, 84, 4),
(2, 30, 104, 14),
(1, 25, 134, 24);